# Generated by Django 5.2.16 on 2026-08-18 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='FinFocus Enterprise', max_length=255)),
                ('tax_id', models.CharField(default='27AAACF1234H1Z5', max_length=50)),
                ('industry', models.CharField(default='SaaS & Tech Services', max_length=100)),
                ('annual_revenue', models.FloatField(default=250000.0)),
                ('monthly_cashflow', models.FloatField(default=20000.0)),
                ('debt_to_income_ratio', models.FloatField(default=28.5)),
                ('gst_filing_compliance', models.FloatField(default=98.0)),
                ('revenue_volatility', models.FloatField(default=4.2)),
                ('credit_age_years', models.FloatField(default=4.5)),
                ('credit_inquiries', models.IntegerField(default=2)),
                ('avg_payment_delay_days', models.IntegerField(default=12)),
                ('expense_ratio', models.FloatField(default=35.0)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('uploaded_files_json', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
