# Generated by Django 5.2.16 on 2026-08-20 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.FloatField()),
                ('loan_purpose', models.CharField(max_length=100)),
                ('tenure_months', models.IntegerField()),
                ('collateral_type', models.CharField(default='Unsecured / Business Cashflow', max_length=100)),
                ('collateral_value', models.FloatField(default=0.0)),
                ('monthly_income', models.FloatField()),
                ('existing_emi', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PRE_APPROVED', 'Pre-Approved with Adjustments'), ('UNDER_REVIEW', 'Under Review'), ('REJECTED', 'Rejected')], default='UNDER_REVIEW', max_length=30)),
                ('approved_amount', models.FloatField(default=0.0)),
                ('interest_rate', models.FloatField(default=10.5)),
                ('monthly_installment', models.FloatField(default=0.0)),
                ('risk_tier', models.CharField(default='Tier B - Moderate Risk', max_length=50)),
                ('underwriting_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
