# Generated by Django 5.2.16 on 2026-09-07 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_loanapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=50, unique=True)),
                ('date', models.CharField(max_length=50)),
                ('merchant', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('credit', 'Credit / Income'), ('debit', 'Debit / Expense')], max_length=20)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Flagged', 'Flagged')], default='Completed', max_length=30)),
                ('payment_method', models.CharField(default='ACH Direct Deposit', max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
