# Generated by Django 5.2.16 on 2026-08-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('business_owner', 'Business Owner'), ('loan_officer', 'Loan Officer')], default='business_owner', max_length=30),
        ),
    ]
